name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: List files in project directory
        run: ls -la ./
      
      - name: Copy README.md to project directory
        run: cp ./README.md ./Otel.Sdk/

      - name: List files in project directory
        run: ls -la ./Otel.Sdk/

      - name: Build the project
        run: dotnet build --configuration Release --no-restore Otel.Sdk/Otel.Sdk.csproj

      - name: Pack the project
        run: dotnet pack --configuration Release --no-build --output ./nupkg Otel.Sdk/Otel.Sdk.csproj

      - name: Publish NuGet Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key $NUGET_API_KEY --source "https://api.nuget.org/v3/index.json"